### ISSUE TITLE
Conventions d'écriture des documentations

### ISSUE THREAD

**Issue by pierreeliseeflory** [titiloltiti/IN204-ObjectOrientedRayTracing#1]
# On en a gros !

## Le problème

Il faudrait établir une convention d'écriture des documents relatifs au projet. En effet, il existe actuellement des documents de type Markdown qui sont débutés en anglais puis rédigés en français.

## Solution 

À partir de maintenant, il s'agirait de rédiger l'entierté du code source et des documentations en anglais afin de proposer une adaptativité du projet à l'international la plus aisée possible.

## Remarque

Pourquoi cet issue est-il rédigé en français alors qu'il prône l'utilisation de la langue anglaise.

**Comment by titiloltiti** [comment]
Oui
